### ISSUE TITLE
「评论」友情链接

### ISSUE THREAD

**Issue by Shanyaliux** [Shanyaliux/comment#59]
页面：https://shanya.world/friends/

**Comment by Shanyaliux** [comment]
欢迎大家来交换友链😁

**Comment by Shanyaliux** [comment]
我是一条示例😉😉😉

```yaml
- name: Shanya's blog # 昵称
  desc: 积跬步以至千里，喜欢学习喜欢你。 # 介绍
  avatar: https://shanya.world/img/avatar.png # 头像
  link: https://shanya.world/  # 链接

```
